name: Unit Tests

on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  run_tests:
    name: Run SwiftPM tests
    runs-on: macos-15
    timeout-minutes: 5
    steps:
      - uses: partout-io/action-prepare-xcode-build@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch SWON submodule
        run: |
          git submodule init vendors/swon
          git submodule update --depth 1 vendors/swon
      - name: Ensure previews are off
        run: |
          expected="let forPreviews = false"
          grep "^$expected" Package.swift
      - name: Ensure Foundation compatibility is off
        run: |
          expected="let useFoundationCompatibility: FoundationCompatibility = .off"
          grep "^$expected" Package.swift
      - name: Run tests
        run: |
          swift test
